"""Pydantic request/response and domain schemas."""

from typing import Any, Literal, Optional

from pydantic import BaseModel, Field


class CreateSessionRequest(BaseModel):
    title: Optional[str] = None
    creator_name: Optional[str] = None


class CreateSessionResponse(BaseModel):
    session_id: str
    user_id: str
    status: str
    system_ws_url: str


class JoinSessionRequest(BaseModel):
    access_code: str
    display_name: Optional[str] = None


class JoinSessionResponse(BaseModel):
    session_id: str
    user_id: str
    title: str
    status: str
    session_ws_url: str


class GitHubExportRequest(BaseModel):
    visibility: Literal["private", "public"] = "private"
    add_pages_workflow: bool = False


class MasterContext(BaseModel):
    """The initial shared context generated by the system agent."""

    title: Optional[str] = None
    objective: str
    scope: str
    target_audience: Optional[str] = None
    deliverables: list[str] = Field(default_factory=list)
    constraints: list[str] = Field(default_factory=list)
    parameters: dict[str, Any] = Field(default_factory=dict)
